// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu7MUSNa6CZav49Vq05BQZSiWFDL0ADeY',
    appId: '1:996559471555:web:fd8dbdf788d2d6a4663376',
    messagingSenderId: '996559471555',
    projectId: 'myportfolio-9730f',
    authDomain: 'myportfolio-9730f.firebaseapp.com',
    storageBucket: 'myportfolio-9730f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuH1T7TzlfsgP_WZQDkBdTsX1WcwvyVQ',
    appId: '1:996559471555:android:149e15b8f080d07c663376',
    messagingSenderId: '996559471555',
    projectId: 'myportfolio-9730f',
    storageBucket: 'myportfolio-9730f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYsUXwVUDJAsYwz8sAasYaYX5lZg9i7M',
    appId: '1:996559471555:ios:781a7304b3028ac9663376',
    messagingSenderId: '996559471555',
    projectId: 'myportfolio-9730f',
    storageBucket: 'myportfolio-9730f.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
